name: pickup right one
on:
 workflow_dispatch:

jobs:
   project-a-or-project-b:
       runs-on: ubuntu-latest
       name: project A or project B

       steps:
       - name: checkout Main repo
         uses: actions/checkout@v2
         with:
           path: .
       - name: Run main repo
         id: main
         run: | 
           status=`ls | grep -i pom.xml`
           echo "$status"
           echo "::set-output name=GREET::status"

       - name: pick one
         if: always() 
         run: |
           echo ${{ steps.main.outputs.GREET }}
         
          #  if ${{ steps.main.outputs }} == 0; 
          #  then
         
          #  echo "this is java project"
          #  echo  "found pom file"
          #  else 
          #  echo "this may be .NET project"
          #  echo  "Not found pom file"
          #  fi

          